language: scala
script:
  - ./travis-test.sh
scala:
   - 2.11.8
jdk:
   - oraclejdk8
before_script:
  - ulimit -c unlimited
  - mkdir $TRAVIS_BUILD_DIR/tmp
  - export SBT_OPTS="-Djava.io.tmpdir=$TRAVIS_BUILD_DIR/tmp"
after_failure:
  "cat /home/travis/build/kamon-io/kamon-agent/hs_err_pid*.log"
sudo: false
